# tasks file for supervisor
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  with_items: "{{ supervisor_dependencies }}"
  when: ansible_pkg_mgr == 'apt'
  tags:
    - supervisor-install-dependencies

- name: install | dependencies
  yum:
    name: "{{ item }}"
    state: "{{ package_install_state | default('latest') }}"
  when: ansible_pkg_mgr == 'yum' or ansible_pkg_mgr == 'dnf'
  with_items: "{{ supervisor_dependencies }}"
  tags:
    - supervisor-install-dependencies

- name: install | supervisor (specific version)
  pip:
    name: supervisor
    version: "{{ supervisor_version }}"
  when: "supervisor_version != 'latest'"
  tags:
    - supervisor-install-specific

- name: install | supervisor (latest version)
  pip:
    name: supervisor
    state: "{{ supervisor_version }}"
  when: "supervisor_version == 'latest'"
  tags:
    - supervisor-install-latest
